project:
  type: website

website:
  title: My Sustainability
  sidebar:
    style: "docked"
    search: false
    contents:
      - index.qmd
      - auto: "modules/*.qmd"

format:
  html:
    page-layout: full