project:
  type: website
  output-dir: docs

website:
  favicon: assets/logo.png
  sidebar:
    style: "docked"
    background: "light"
    search: false
    border: true
    logo: assets/logo.png
    footer: Powered By ![](/assets/epfl-logo.svg){width=50%}
    contents:
      - file: index.qmd
        icon: "bar-chart"
      - file: modules/travel.qmd
        icon: "airplane"
      - file: modules/food.qmd
        icon: "cup-hot"
      - file: modules/compute.qmd
        icon: "cpu"


format:
  html:
    theme:
      # can use any of the following themes (below are ones with white bg):
      # https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/bootstrap/themes
      #- sketchy
      #- simplex
      #- sandstone
      #- minty
      #- materia
      #- lumen
      #- flatly
      #- cosmo
      #- pulse
      - lux
    grid:
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    toc: true
